## Dataframes

In [1]:
dict_1={"Grocerylist":['soap','shampoo','conditioner','waterbottle'],"Price":[50,400,350,100]}
dict_1

{'Grocerylist': ['soap', 'shampoo', 'conditioner', 'waterbottle'],
 'Price': [50, 400, 350, 100]}

In [9]:
$pip install pandas

SyntaxError: invalid syntax (1907001699.py, line 1)

In [11]:
import pandas as pd
pd.DataFrame(dict_1)

   Grocerylist  Price
0         soap     50
1      shampoo    400
2  conditioner    350
3  waterbottle    100

In [12]:
dict_2={"Actors":['vijay','kamal','rajini','ajith'],"Title":["Thalapathy","Ulaganayagan","Superstar","Ultimate Star"]}
dict_2

{'Actors': ['vijay', 'kamal', 'rajini', 'ajith'],
 'Title': ['Thalapathy', 'Ulaganayagan', 'Superstar', 'Ultimate Star']}

In [13]:
pd.DataFrame(dict_2)

   Actors          Title
0   vijay     Thalapathy
1   kamal   Ulaganayagan
2  rajini      Superstar
3   ajith  Ultimate Star

In [15]:
dict_3={"Achievers":['UsainBolt','Neeraj Chopra','Muhammad Ali'],"Records":[100,87.58,3],"Sports":['100M race','javelin throw','Boxing']}
pd.DataFrame(dict_3)

       Achievers  Records         Sports
0      UsainBolt   100.00      100M race
1  Neeraj Chopra    87.58  javelin throw
2   Muhammad Ali     3.00         Boxing